package com.cegedimassurance.ws.servicesassures.wsdl;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:53.475+01:00 Generated source
 * version: 3.1.13
 */
@WebServiceClient(
    name = "FSIQServicesAssures",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_assures.wsdl",
    targetNamespace = "http://ws.cegedimassurance.com/servicesassures/wsdl")
public class FSIQServicesAssures extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName("http://ws.cegedimassurance.com/servicesassures/wsdl", "FSIQServicesAssures");
  public static final QName ServicesAssuresPort =
      new QName("http://ws.cegedimassurance.com/servicesassures/wsdl", "ServicesAssuresPort");

  static {
    URL url = null;
    try {
      url =
          new URL(
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_assures.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(FSIQServicesAssures.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_assures.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public FSIQServicesAssures(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public FSIQServicesAssures(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public FSIQServicesAssures() {
    super(WSDL_LOCATION, SERVICE);
  }

  /**
   * @return returns ServicesAssures
   */
  @WebEndpoint(name = "ServicesAssuresPort")
  public ServicesAssures getServicesAssuresPort() {
    return super.getPort(ServicesAssuresPort, ServicesAssures.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns ServicesAssures
   */
  @WebEndpoint(name = "ServicesAssuresPort")
  public ServicesAssures getServicesAssuresPort(WebServiceFeature... features) {
    return super.getPort(ServicesAssuresPort, ServicesAssures.class, features);
  }
}
