/** Please modify this class to meet your needs This class is not complete */
package com.cegedimassurance.ws.servicesassures.wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:53.450+01:00 Generated source
 * version: 3.1.13
 */
@jakarta.jws.WebService(
    serviceName = "FSIQServicesAssures",
    portName = "ServicesAssuresPort",
    targetNamespace = "http://ws.cegedimassurance.com/servicesassures/wsdl",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_assures.wsdl",
    endpointInterface = "com.cegedimassurance.ws.servicesassures.wsdl.ServicesAssures")
public class ServicesAssuresPortImpl implements ServicesAssures {

  private static final Logger LOG = Logger.getLogger(ServicesAssuresPortImpl.class.getName());

  /*
   * (non-Javadoc)
   *
   * @see
   * com.cegedimassurance.ws.servicesassures.wsdl.ServicesAssures#getCarteTPData(
   * com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire
   * requeteBeneficiaire)*
   */
  public com.cegedimassurances.norme.carte.ReponseCarteTP getCarteTPData(
      com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire requeteBeneficiaire) {
    LOG.info("Executing operation getCarteTPData");
    System.out.println(requeteBeneficiaire);
    try {
      com.cegedimassurances.norme.carte.ReponseCarteTP _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   *
   * @see
   * com.cegedimassurance.ws.servicesassures.wsdl.ServicesAssures#getCarteTPOTP(
   * com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire
   * requeteBeneficiaire)*
   */
  public com.cegedimassurances.norme.commun.ReponseCommun getCarteTPOTP(
      com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire requeteBeneficiaire) {
    LOG.info("Executing operation getCarteTPOTP");
    System.out.println(requeteBeneficiaire);
    try {
      com.cegedimassurances.norme.commun.ReponseCommun _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.servicesassures.wsdl.ServicesAssures#
   * getServicesOuverts(com.cegedimassurances.norme.beneficiaire.
   * RequeteBeneficiaire requeteBeneficiaire)*
   */
  public com.cegedimassurances.norme.abonnement.ReponseAbonnement getServicesOuverts(
      com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire requeteBeneficiaire) {
    LOG.info("Executing operation getServicesOuverts");
    System.out.println(requeteBeneficiaire);
    try {
      com.cegedimassurances.norme.abonnement.ReponseAbonnement _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }
}
