package com.cegedimassurance.ws.servicesassures.wsdl;

/** Please modify this class to meet your needs This class is not complete */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:53.379+01:00 Generated source
 * version: 3.1.13
 */
public final class ServicesAssures_ServicesAssuresPort_Client {

  private static final QName SERVICE_NAME =
      new QName("http://ws.cegedimassurance.com/servicesassures/wsdl", "FSIQServicesAssures");

  private ServicesAssures_ServicesAssuresPort_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = FSIQServicesAssures.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    FSIQServicesAssures ss = new FSIQServicesAssures(wsdlURL, SERVICE_NAME);
    ServicesAssures port = ss.getServicesAssuresPort();

    {
      System.out.println("Invoking getCarteTPData...");
      com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire
          _getCarteTPData_requeteBeneficiaire = null;
      com.cegedimassurances.norme.carte.ReponseCarteTP _getCarteTPData__return =
          port.getCarteTPData(_getCarteTPData_requeteBeneficiaire);
      System.out.println("getCarteTPData.result=" + _getCarteTPData__return);
    }
    {
      System.out.println("Invoking getCarteTPOTP...");
      com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire
          _getCarteTPOTP_requeteBeneficiaire = null;
      com.cegedimassurances.norme.commun.ReponseCommun _getCarteTPOTP__return =
          port.getCarteTPOTP(_getCarteTPOTP_requeteBeneficiaire);
      System.out.println("getCarteTPOTP.result=" + _getCarteTPOTP__return);
    }
    {
      System.out.println("Invoking getServicesOuverts...");
      com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire
          _getServicesOuverts_requeteBeneficiaire = null;
      com.cegedimassurances.norme.abonnement.ReponseAbonnement _getServicesOuverts__return =
          port.getServicesOuverts(_getServicesOuverts_requeteBeneficiaire);
      System.out.println("getServicesOuverts.result=" + _getServicesOuverts__return);
    }

    System.exit(0);
  }
}
