package com.cegedimassurance.ws.servicesassures.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:53.467+01:00 Generated source
 * version: 3.1.13
 */
@WebService(
    targetNamespace = "http://ws.cegedimassurance.com/servicesassures/wsdl",
    name = "ServicesAssures")
@XmlSeeAlso({
  com.cegedimassurances.norme.abonnement.ObjectFactory.class,
  com.cegedimassurances.norme.amc.ObjectFactory.class,
  com.cegedimassurances.norme.beneficiaire.ObjectFactory.class,
  com.cegedimassurances.norme.commun.ObjectFactory.class,
  com.cegedimassurances.norme.carte.ObjectFactory.class
})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicesAssures {

  /** Obtention des données permettant la construction de la carte */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicesassures/wsdl/getCarteTPData")
  @WebResult(name = "reponse_carteTP", targetNamespace = "", partName = "reponse_carteTP")
  public com.cegedimassurances.norme.carte.ReponseCarteTP getCarteTPData(
      @WebParam(
              partName = "requete_beneficiaire",
              name = "requete_beneficiaire",
              targetNamespace = "")
          com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire requeteBeneficiaire);

  /** Obtention d'un n° OTP à destination d'un PS */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicesassures/wsdl/getCarteTPOTP")
  @WebResult(name = "reponse_commun", targetNamespace = "", partName = "reponse_commun")
  public com.cegedimassurances.norme.commun.ReponseCommun getCarteTPOTP(
      @WebParam(
              partName = "requete_beneficiaire",
              name = "requete_beneficiaire",
              targetNamespace = "")
          com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire requeteBeneficiaire);

  /** Appel de l'abonnement beneficiaire */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicesassures/wsdl/getServicesOuverts")
  @WebResult(name = "reponse_abonnement", targetNamespace = "", partName = "reponse_abonnement")
  public com.cegedimassurances.norme.abonnement.ReponseAbonnement getServicesOuverts(
      @WebParam(
              partName = "requete_beneficiaire",
              name = "requete_beneficiaire",
              targetNamespace = "")
          com.cegedimassurances.norme.beneficiaire.RequeteBeneficiaire requeteBeneficiaire);
}
