/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    // #################### TRANSCODING OBJECT ##########################
    SEARCH_PARAM_CONTRAT_INDIV: { type: 'SEARCH_PARAM_CONTRAT_INDIV' },
    SEARCH_PARAM_CONTRAT_INDIV_PENDING: { type: 'SEARCH_PARAM_CONTRAT_INDIV_PENDING' },
    SEARCH_PARAM_CONTRAT_INDIV_FULFILLED: { type: 'SEARCH_PARAM_CONTRAT_INDIV_FULFILLED' },
    SEARCH_PARAM_CONTRAT_INDIV_REJECTED: { type: 'SEARCH_PARAM_CONTRAT_INDIV_REJECTED' },

    GENERATE_PARAMETRAGE_CONTRAT: { type: 'GENERATE_PARAMETRAGE_CONTRAT' },
    GENERATE_PARAMETRAGE_CONTRAT_PENDING: { type: 'GENERATE_PARAMETRAGE_CONTRAT_PENDING' },
    GENERATE_PARAMETRAGE_CONTRAT_FULFILLED: { type: 'GENERATE_PARAMETRAGE_CONTRAT_FULFILLED' },
    GENERATE_PARAMETRAGE_CONTRAT_REJECTED: { type: 'GENERATE_PARAMETRAGE_CONTRAT_REJECTED' },

    SEARCH_DECLARANT: { type: 'SEARCH_DECLARANT' },
    SEARCH_DECLARANT_PENDING: { type: 'SEARCH_DECLARANT_PENDING' },
    SEARCH_DECLARANT_FULFILLED: { type: 'SEARCH_DECLARANT_FULFILLED' },
    SEARCH_DECLARANT_REJECTED: { type: 'SEARCH_DECLARANT_REJECTED' },
};
