/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    // #################### TRANSCODING OBJECT ##########################
    GET_PARAM_DROIT_REF: { type: 'GET_PARAM_DROIT_REF' },
    GET_PARAM_DROIT_REF_PENDING: { type: 'GET_PARAM_DROIT_REF_PENDING' },
    GET_PARAM_DROIT_REF_FULFILLED: { type: 'GET_PARAM_DROIT_REF_FULFILLED' },
    GET_PARAM_DROIT_REF_REJECTED: { type: 'GET_PARAM_DROIT_REF_REJECTED' },
    GET_OFFERS: { type: 'GET_OFFERS' },
    GET_OFFERS_PENDING: { type: 'GET_OFFERS_PENDING' },
    GET_OFFERS_FULFILLED: { type: 'GET_OFFERS_FULFILLED' },
    GET_OFFERS_REJECTED: { type: 'GET_OFFERS_REJECTED' },
    CREATE_PARAM_DROIT: { type: 'CREATE_PARAM_DROIT' },
    CREATE_PARAM_DROIT_PENDING: { type: 'CREATE_PARAM_DROIT_PENDING' },
    CREATE_PARAM_DROIT_FULFILLED: { type: 'CREATE_PARAM_DROIT_FULFILLED' },
    GET_CODES_ITELIS: { type: 'GET_CODES_ITELIS' },
    GET_CODES_ITELIS_PENDING: { type: 'GET_CODES_ITELIS_PENDING' },
    GET_CODES_ITELIS_FULFILLED: { type: 'GET_CODES_ITELIS_FULFILLED' },
    GET_CODES_ITELIS_REJECTED: { type: 'GET_CODES_ITELIS_REJECTED' },
    GET_DOMAINES_TP: { type: 'GET_DOMAINES_TP' },
    GET_DOMAINES_TP_PENDING: { type: 'GET_DOMAINES_TP_PENDING' },
    GET_DOMAINES_TP_FULFILLED: { type: 'GET_DOMAINES_TP_FULFILLED' },
    GET_DOMAINES_TP_REJECTED: { type: 'GET_DOMAINES_TP_REJECTED' },
    REINIT_OFFERS: { type: 'REINIT_OFFERS' },
    GET_PRIORITE_PARAM: { type: 'GET_PRIORITE_PARAM' },
    GET_PRIORITE_PARAM_FULFILLED: { type: 'GET_PRIORITE_PARAM_FULFILLED' },
    GET_ONE_PARAM: { type: 'GET_ONE_PARAM' },
    GET_ONE_PARAM_PENDING: { type: 'GET_ONE_PARAM_PENDING' },
    GET_ONE_PARAM_FULFILLED: { type: 'GET_ONE_PARAM_FULFILLED' },
    GET_ONE_PARAM_REJECTED: { type: 'GET_ONE_PARAM_REJECTED' },
};
