/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    SEARCH_TRIGGERS: { type: 'SEARCH_TRIGGERS' },
    SEARCH_TRIGGERS_PENDING: { type: 'SEARCH_TRIGGERS_PENDING' },
    SEARCH_TRIGGERS_FULFILLED: { type: 'SEARCH_TRIGGERS_FULFILLED' },
    SEARCH_TRIGGERS_REJECTED: { type: 'SEARCH_TRIGGERS_REJECTED' },
    GET_KO_TRIGGERED_BENEFICIARIES: { type: 'GET_KO_TRIGGERED_BENEFICIARIES' },
    GET_KO_TRIGGERED_BENEFICIARIES_PENDING: { type: 'GET_KO_TRIGGERED_BENEFICIARIES_PENDING' },
    GET_KO_TRIGGERED_BENEFICIARIES_FULFILLED: { type: 'GET_KO_TRIGGERED_BENEFICIARIES_FULFILLED' },
    GET_KO_TRIGGERED_BENEFICIARIES_REJECTED: { type: 'GET_KO_TRIGGERED_BENEFICIARIES_REJECTED' },
    CALL_RECYCLE: { type: 'CALL_RECYCLE' },
    CALL_RECYCLE_PENDING: { type: 'CALL_RECYCLE_PENDING' },
    CALL_RECYCLE_FULFILLED: { type: 'CALL_RECYCLE_FULFILLED' },
    CALL_RECYCLE_REJECTED: { type: 'CALL_RECYCLE_REJECTED' },
    CALL_CANCEL_PROCESS: { type: 'CALL_CANCEL_PROCESS' },
    CALL_CANCEL_PROCESS_PENDING: { type: 'CALL_CANCEL_PROCESS_PENDING' },
    CALL_CANCEL_PROCESS_FULFILLED: { type: 'CALL_CANCEL_PROCESS_FULFILLED' },
    CALL_CANCEL_PROCESS_REJECTED: { type: 'CALL_CANCEL_PROCESS_REJECTED' },
    CALL_TRIGGER_GENERATION: { type: 'CALL_TRIGGER_GENERATION' },
    CALL_TRIGGER_GENERATION_PENDING: { type: 'CALL_TRIGGER_GENERATION_PENDING' },
    CALL_TRIGGER_GENERATION_FULFILLED: { type: 'CALL_TRIGGER_GENERATION_FULFILLED' },
    CALL_TRIGGER_GENERATION_REJECTED: { type: 'CALL_TRIGGER_GENERATION_REJECTED' },
    CALL_TRIGGER_ABANDON: { type: 'CALL_TRIGGER_ABANDON' },
    CALL_TRIGGER_ABANDON_PENDING: { type: 'CALL_TRIGGER_ABANDON_PENDING' },
    CALL_TRIGGER_ABANDON_FULFILLED: { type: 'CALL_TRIGGER_ABANDON_FULFILLED' },
    CALL_TRIGGER_ABANDON_REJECTED: { type: 'CALL_TRIGGER_ABANDON_REJECTED' },
};
