package com.cegedimassurances.norme.abonnement;

/** Please modify this class to meet your needs This class is not complete */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:58.420+01:00 Generated source
 * version: 3.1.13
 */
public final class WSABONNEMENT_WSABONNEMENT_Client {

  private static final QName SERVICE_NAME =
      new QName("http://norme.cegedimassurances.com/abonnement/", "wsAbonnementWSDL");

  private WSABONNEMENT_WSABONNEMENT_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = WsAbonnementWSDL.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    WsAbonnementWSDL ss = new WsAbonnementWSDL(wsdlURL, SERVICE_NAME);
    WSABONNEMENT port = ss.getWSABONNEMENT();

    {
      System.out.println("Invoking getAbonnement...");
      com.cegedimassurances.norme.abonnement.GetAbonnementIn _getAbonnement_parameters = null;
      com.cegedimassurances.norme.abonnement.GetAbonnementOut _getAbonnement__return =
          port.getAbonnement(_getAbonnement_parameters);
      System.out.println("getAbonnement.result=" + _getAbonnement__return);
    }

    System.exit(0);
  }
}
