package com.cegedimassurances.norme.abonnement;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:58.450+01:00 Generated source
 * version: 3.1.13
 */
@WebServiceClient(
    name = "wsAbonnementWSDL",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/abonnement.wsdl",
    targetNamespace = "http://norme.cegedimassurances.com/abonnement/")
public class WsAbonnementWSDL extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName("http://norme.cegedimassurances.com/abonnement/", "wsAbonnementWSDL");
  public static final QName WSABONNEMENT =
      new QName("http://norme.cegedimassurances.com/abonnement/", "WSABONNEMENT");

  static {
    URL url = null;
    try {
      url =
          new URL(
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/abonnement.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(WsAbonnementWSDL.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/abonnement.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public WsAbonnementWSDL(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public WsAbonnementWSDL(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public WsAbonnementWSDL() {
    super(WSDL_LOCATION, SERVICE);
  }

  /**
   * @return returns WSABONNEMENT
   */
  @WebEndpoint(name = "WSABONNEMENT")
  public WSABONNEMENT getWSABONNEMENT() {
    return super.getPort(WSABONNEMENT, WSABONNEMENT.class);
  }

  /**
   * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns WSABONNEMENT
   */
  @WebEndpoint(name = "WSABONNEMENT")
  public WSABONNEMENT getWSABONNEMENT(WebServiceFeature... features) {
    return super.getPort(WSABONNEMENT, WSABONNEMENT.class, features);
  }
}
