package com.cegedimassurances.norme.abonnement;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:58.440+01:00 Generated source
 * version: 3.1.13
 */
@WebService(
    targetNamespace = "http://norme.cegedimassurances.com/abonnement/",
    name = "WSABONNEMENT")
@XmlSeeAlso({
  ObjectFactory.class,
  com.cegedimassurances.norme.amc.ObjectFactory.class,
  com.cegedimassurances.norme.beneficiaire.ObjectFactory.class,
  com.cegedimassurances.norme.amo.ObjectFactory.class,
  com.cegedimassurances.norme.commun.ObjectFactory.class,
  com.cegedimassurances.norme.patient.ObjectFactory.class,
  com.cegedimassurances.norme.ps.ObjectFactory.class
})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WSABONNEMENT {

  @WebMethod(action = "http://ws.cegedim-activ.com/wsAbonnement/getAbonnement")
  @WebResult(
      name = "getAbonnementOut",
      targetNamespace = "http://norme.cegedimassurances.com/abonnement/",
      partName = "parameters")
  public GetAbonnementOut getAbonnement(
      @WebParam(
              partName = "parameters",
              name = "getAbonnementIn",
              targetNamespace = "http://norme.cegedimassurances.com/abonnement/")
          GetAbonnementIn parameters);
}
