/** Please modify this class to meet your needs This class is not complete */
package com.cegedimassurances.norme.abonnement;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:58.430+01:00 Generated source
 * version: 3.1.13
 */
@jakarta.jws.WebService(
    serviceName = "wsAbonnementWSDL",
    portName = "WSABONNEMENT",
    targetNamespace = "http://norme.cegedimassurances.com/abonnement/",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/abonnement.wsdl",
    endpointInterface = "com.cegedimassurances.norme.abonnement.WSABONNEMENT")
public class WSABONNEMENTImpl implements WSABONNEMENT {

  private static final Logger LOG = Logger.getLogger(WSABONNEMENTImpl.class.getName());

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurances.norme.abonnement.WSABONNEMENT#getAbonnement(com.
   * cegedimassurances.norme.abonnement.GetAbonnementIn parameters)*
   */
  public com.cegedimassurances.norme.abonnement.GetAbonnementOut getAbonnement(
      GetAbonnementIn parameters) {
    LOG.info("Executing operation getAbonnement");
    System.out.println(parameters);
    try {
      com.cegedimassurances.norme.abonnement.GetAbonnementOut _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }
}
