/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    GET_ALL_VOLUMETRY: { type: 'GET_ALL_VOLUMETRY' },
    GET_ALL_VOLUMETRY_PENDING: { type: 'GET_ALL_VOLUMETRY_PENDING' },
    GET_ALL_VOLUMETRY_FULFILLED: { type: 'GET_ALL_VOLUMETRY_FULFILLED' },
    GET_ALL_VOLUMETRY_REJECTED: { type: 'GET_ALL_VOLUMETRY_REJECTED' },

    GET_ALL_DECLARANT: { type: 'GET_ALL_DECLARANT' },
    GET_ALL_DECLARANT_PENDING: { type: 'GET_ALL_DECLARANT_PENDING' },
    GET_ALL_DECLARANT_FULFILLED: { type: 'GET_ALL_DECLARANT_FULFILLED' },
    GET_ALL_DECLARANT_REJECTED: { type: 'GET_ALL_DECLARANT_REJECTED' },

    CHANGE_VOLUMETRY_SEARCH_CRITERIA: { type: 'CHANGE_VOLUMETRY_SEARCH_CRITERIA' },
};
