package com.cegedimassurance.ws.servicestarificationprescription.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:02.834+01:00 Generated source
 * version: 3.1.13
 */
@WebService(
    targetNamespace = "http://ws.cegedimassurance.com/servicestarificationprescription/wsdl",
    name = "ServicesTarificationprescription")
@XmlSeeAlso({
  com.cegedimassurances.norme.tarification_prescription.ObjectFactory.class,
  com.cegedimassurances.norme.commun.ObjectFactory.class
})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicesTarificationprescription {

  /**
   * Appel du service prise en charge de la tarification. Dans le header de la réponse doit être
   * renseigné le numéro d'accréditation.
   */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicestarificationprescription/wsdl/getPec")
  @WebResult(name = "getTarification_out", targetNamespace = "", partName = "getTarification_out")
  public com.cegedimassurances.norme.tarification_prescription.GetTarificationOut getPec(
      @WebParam(partName = "getTarification_in", name = "getTarification_in", targetNamespace = "")
          com.cegedimassurances.norme.tarification_prescription.GetTarificationIn
              getTarificationIn);

  /** Appel du service de devis de la tarification */
  @WebMethod(
      action = "http://ws.cegedimassurance.com/servicestarificationprescription/wsdl/getDevis")
  @WebResult(name = "getTarification_out", targetNamespace = "", partName = "getTarification_out")
  public com.cegedimassurances.norme.tarification_prescription.GetTarificationOut getDevis(
      @WebParam(partName = "getTarification_in", name = "getTarification_in", targetNamespace = "")
          com.cegedimassurances.norme.tarification_prescription.GetTarificationIn
              getTarificationIn);
}
