/** Please modify this class to meet your needs This class is not complete */
package com.cegedimassurance.ws.servicestarificationprescription.wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:02.827+01:00 Generated source
 * version: 3.1.13
 */
@jakarta.jws.WebService(
    serviceName = "FSIQServicesTarification",
    portName = "ServicesTarificationPort",
    targetNamespace = "http://ws.cegedimassurance.com/servicestarificationprescription/wsdl",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_tarification_prescription.wsdl",
    endpointInterface =
        "com.cegedimassurance.ws.servicestarificationprescription.wsdl.ServicesTarificationprescription")
public class ServicesTarificationPortImpl implements ServicesTarificationprescription {

  private static final Logger LOG = Logger.getLogger(ServicesTarificationPortImpl.class.getName());

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.servicestarificationprescription.wsdl.
   * ServicesTarificationprescription#getPec(com.cegedimassurances.norme.
   * tarification_prescription.GetTarificationIn getTarificationIn)*
   */
  public com.cegedimassurances.norme.tarification_prescription.GetTarificationOut getPec(
      com.cegedimassurances.norme.tarification_prescription.GetTarificationIn getTarificationIn) {
    LOG.info("Executing operation getPec");
    System.out.println(getTarificationIn);
    try {
      com.cegedimassurances.norme.tarification_prescription.GetTarificationOut _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.servicestarificationprescription.wsdl.
   * ServicesTarificationprescription#getDevis(com.cegedimassurances.norme.
   * tarification_prescription.GetTarificationIn getTarificationIn)*
   */
  public com.cegedimassurances.norme.tarification_prescription.GetTarificationOut getDevis(
      com.cegedimassurances.norme.tarification_prescription.GetTarificationIn getTarificationIn) {
    LOG.info("Executing operation getDevis");
    System.out.println(getTarificationIn);
    try {
      com.cegedimassurances.norme.tarification_prescription.GetTarificationOut _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }
}
