package com.cegedimassurance.ws.servicestarificationprescription.wsdl;

/** Please modify this class to meet your needs This class is not complete */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:02.817+01:00 Generated source
 * version: 3.1.13
 */
public final class ServicesTarificationprescription_ServicesTarificationPort_Client {

  private static final QName SERVICE_NAME =
      new QName(
          "http://ws.cegedimassurance.com/servicestarificationprescription/wsdl",
          "FSIQServicesTarification");

  private ServicesTarificationprescription_ServicesTarificationPort_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = FSIQServicesTarification.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    FSIQServicesTarification ss = new FSIQServicesTarification(wsdlURL, SERVICE_NAME);
    ServicesTarificationprescription port = ss.getServicesTarificationPort();

    {
      System.out.println("Invoking getPec...");
      com.cegedimassurances.norme.tarification_prescription.GetTarificationIn
          _getPec_getTarificationIn = null;
      com.cegedimassurances.norme.tarification_prescription.GetTarificationOut _getPec__return =
          port.getPec(_getPec_getTarificationIn);
      System.out.println("getPec.result=" + _getPec__return);
    }
    {
      System.out.println("Invoking getDevis...");
      com.cegedimassurances.norme.tarification_prescription.GetTarificationIn
          _getDevis_getTarificationIn = null;
      com.cegedimassurances.norme.tarification_prescription.GetTarificationOut _getDevis__return =
          port.getDevis(_getDevis_getTarificationIn);
      System.out.println("getDevis.result=" + _getDevis__return);
    }

    System.exit(0);
  }
}
