package com.cegedimassurance.ws.basededroit.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:57.278+01:00 Generated source
 * version: 3.1.13
 */
@WebService(
    targetNamespace = "http://ws.cegedimassurance.com/basededroit/wsdl",
    name = "BaseDeDroit")
@XmlSeeAlso({
  com.cegedimassurances.norme.amc.ObjectFactory.class,
  com.cegedimassurances.norme.beneficiaire.ObjectFactory.class,
  com.cegedimassurances.norme.commun.ObjectFactory.class,
  com.cegedimassurances.norme.base_de_droit.ObjectFactory.class
})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BaseDeDroit {

  /** Recuperation des données présente dans la base de droit */
  @WebMethod
  @WebResult(name = "getInfoBddResponse", targetNamespace = "", partName = "getInfoBddResponse")
  public com.cegedimassurances.norme.base_de_droit.GetInfoBddResponse getInfoBdd(
      @WebParam(partName = "getInfoBddRequest", name = "getInfoBddRequest", targetNamespace = "")
          com.cegedimassurances.norme.base_de_droit.GetInfoBddRequest getInfoBddRequest);
}
