/** Please modify this class to meet your needs This class is not complete */
package com.cegedimassurance.ws.basededroit.wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:57.258+01:00 Generated source
 * version: 3.1.13
 */
@jakarta.jws.WebService(
    serviceName = "$service.ServiceName",
    targetNamespace = "$service.Namespace",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/base_de_droit.wsdl",
    endpointInterface = "com.cegedimassurance.ws.basededroit.wsdl.BaseDeDroit")
public class BaseDeDroitImpl implements BaseDeDroit {

  private static final Logger LOG = Logger.getLogger(BaseDeDroitImpl.class.getName());

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.basededroit.wsdl.BaseDeDroit#getInfoBdd(com.
   * cegedimassurances.norme.base_de_droit.GetInfoBddRequest getInfoBddRequest)*
   */
  public com.cegedimassurances.norme.base_de_droit.GetInfoBddResponse getInfoBdd(
      com.cegedimassurances.norme.base_de_droit.GetInfoBddRequest getInfoBddRequest) {
    LOG.info("Executing operation getInfoBdd");
    System.out.println(getInfoBddRequest);
    try {
      com.cegedimassurances.norme.base_de_droit.GetInfoBddResponse _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }
}
