package com.cegedimassurance.ws.servicestarificationprescriptionchiffree.wsdl;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:03.247+01:00 Generated source
 * version: 3.1.13
 */
@WebServiceClient(
    name = "FSIQServicesTarificationChiffree",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_tarification_prescription_chiffree.wsdl",
    targetNamespace =
        "http://ws.cegedimassurance.com/servicestarificationprescriptionchiffree/wsdl")
public class FSIQServicesTarificationChiffree extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName(
          "http://ws.cegedimassurance.com/servicestarificationprescriptionchiffree/wsdl",
          "FSIQServicesTarificationChiffree");
  public static final QName ServicesTarificationPort =
      new QName(
          "http://ws.cegedimassurance.com/servicestarificationprescriptionchiffree/wsdl",
          "ServicesTarificationPort");

  static {
    URL url = null;
    try {
      url =
          new URL(
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_tarification_prescription_chiffree.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(FSIQServicesTarificationChiffree.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_tarification_prescription_chiffree.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public FSIQServicesTarificationChiffree(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public FSIQServicesTarificationChiffree(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public FSIQServicesTarificationChiffree() {
    super(WSDL_LOCATION, SERVICE);
  }

  /**
   * @return returns ServicesTarificationprescriptionchiffree
   */
  @WebEndpoint(name = "ServicesTarificationPort")
  public ServicesTarificationprescriptionchiffree getServicesTarificationPort() {
    return super.getPort(ServicesTarificationPort, ServicesTarificationprescriptionchiffree.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns ServicesTarificationprescriptionchiffree
   */
  @WebEndpoint(name = "ServicesTarificationPort")
  public ServicesTarificationprescriptionchiffree getServicesTarificationPort(
      WebServiceFeature... features) {
    return super.getPort(
        ServicesTarificationPort, ServicesTarificationprescriptionchiffree.class, features);
  }
}
