package com.cegedimassurance.ws.servicestarificationprescriptionchiffree.wsdl;

/** Please modify this class to meet your needs This class is not complete */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:03.228+01:00 Generated source
 * version: 3.1.13
 */
public final class ServicesTarificationprescriptionchiffree_ServicesTarificationPort_Client {

  private static final QName SERVICE_NAME =
      new QName(
          "http://ws.cegedimassurance.com/servicestarificationprescriptionchiffree/wsdl",
          "FSIQServicesTarificationChiffree");

  private ServicesTarificationprescriptionchiffree_ServicesTarificationPort_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = FSIQServicesTarificationChiffree.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    FSIQServicesTarificationChiffree ss =
        new FSIQServicesTarificationChiffree(wsdlURL, SERVICE_NAME);
    ServicesTarificationprescriptionchiffree port = ss.getServicesTarificationPort();

    {
      System.out.println("Invoking getPec...");
      com.cegedimassurances.norme.tarification_prescription_chiffree.RequeteTarification
          _getPec_requeteTarification = null;
      com.cegedimassurances.norme.tarification_prescription_chiffree.ReponseTarification
          _getPec__return = port.getPec(_getPec_requeteTarification);
      System.out.println("getPec.result=" + _getPec__return);
    }
    {
      System.out.println("Invoking getDevis...");
      com.cegedimassurances.norme.tarification_prescription_chiffree.RequeteTarification
          _getDevis_requeteTarification = null;
      com.cegedimassurances.norme.tarification_prescription_chiffree.ReponseTarification
          _getDevis__return = port.getDevis(_getDevis_requeteTarification);
      System.out.println("getDevis.result=" + _getDevis__return);
    }

    System.exit(0);
  }
}
