/** Please modify this class to meet your needs This class is not complete */
package com.cegedimassurance.ws.servicestarificationprescriptionchiffree.wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:03.235+01:00 Generated source
 * version: 3.1.13
 */
@jakarta.jws.WebService(
    serviceName = "FSIQServicesTarificationChiffree",
    portName = "ServicesTarificationPort",
    targetNamespace =
        "http://ws.cegedimassurance.com/servicestarificationprescriptionchiffree/wsdl",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_tarification_prescription_chiffree.wsdl",
    endpointInterface =
        "com.cegedimassurance.ws.servicestarificationprescriptionchiffree.wsdl.ServicesTarificationprescriptionchiffree")
public class ServicesTarificationPortImpl implements ServicesTarificationprescriptionchiffree {

  private static final Logger LOG = Logger.getLogger(ServicesTarificationPortImpl.class.getName());

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.servicestarificationprescriptionchiffree.wsdl.
   * ServicesTarificationprescriptionchiffree#getPec(com.cegedimassurances.norme.
   * tarification_prescription_chiffree.RequeteTarification requeteTarification)*
   */
  public com.cegedimassurances.norme.tarification_prescription_chiffree.ReponseTarification getPec(
      com.cegedimassurances.norme.tarification_prescription_chiffree.RequeteTarification
          requeteTarification) {
    LOG.info("Executing operation getPec");
    System.out.println(requeteTarification);
    try {
      com.cegedimassurances.norme.tarification_prescription_chiffree.ReponseTarification _return =
          null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.servicestarificationprescriptionchiffree.wsdl.
   * ServicesTarificationprescriptionchiffree#getDevis(com.cegedimassurances.norme
   * .tarification_prescription_chiffree.RequeteTarification requeteTarification)*
   */
  public com.cegedimassurances.norme.tarification_prescription_chiffree.ReponseTarification
      getDevis(
          com.cegedimassurances.norme.tarification_prescription_chiffree.RequeteTarification
              requeteTarification) {
    LOG.info("Executing operation getDevis");
    System.out.println(requeteTarification);
    try {
      com.cegedimassurances.norme.tarification_prescription_chiffree.ReponseTarification _return =
          null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }
}
