package com.cegedimassurance.ws.servicestarificationprescriptionchiffree.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:03.241+01:00 Generated source
 * version: 3.1.13
 */
@WebService(
    targetNamespace =
        "http://ws.cegedimassurance.com/servicestarificationprescriptionchiffree/wsdl",
    name = "ServicesTarificationprescriptionchiffree")
@XmlSeeAlso({
  com.cegedimassurances.norme.tarification_prescription_chiffree.ObjectFactory.class,
  com.cegedimassurances.norme.commun.ObjectFactory.class
})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicesTarificationprescriptionchiffree {

  /**
   * Appel du service prise en charge de la tarification. Dans le header de la réponse doit être
   * renseigné le numéro d'accréditation.
   */
  @WebMethod(
      action =
          "http://ws.cegedimassurance.com/servicestarificationprescriptionchiffree/wsdl/getPec")
  @WebResult(name = "reponse_tarification", targetNamespace = "", partName = "reponse_tarification")
  public com.cegedimassurances.norme.tarification_prescription_chiffree.ReponseTarification getPec(
      @WebParam(
              partName = "requete_tarification",
              name = "requete_tarification",
              targetNamespace = "")
          com.cegedimassurances.norme.tarification_prescription_chiffree.RequeteTarification
              requeteTarification);

  /** Appel du service de devis de la tarification */
  @WebMethod(
      action =
          "http://ws.cegedimassurance.com/servicestarificationprescriptionchiffree/wsdl/getDevis")
  @WebResult(name = "reponse_tarification", targetNamespace = "", partName = "reponse_tarification")
  public com.cegedimassurances.norme.tarification_prescription_chiffree.ReponseTarification
      getDevis(
          @WebParam(
                  partName = "requete_tarification",
                  name = "requete_tarification",
                  targetNamespace = "")
              com.cegedimassurances.norme.tarification_prescription_chiffree.RequeteTarification
                  requeteTarification);
}
