/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    // #################### TRANSCODING OBJECT ##########################
    GET_ALL_PARAM_TRANSCO: { type: 'GET_ALL_PARAM_TRANSCO' },
    GET_ALL_PARAM_TRANSCO_PENDING: { type: 'GET_ALL_PARAM_TRANSCO_PENDING' },
    GET_ALL_PARAM_TRANSCO_FULFILLED: { type: 'GET_ALL_PARAM_TRANSCO_FULFILLED' },

    CREATE_PARAM_TRANSCO: { type: 'CREATE_PARAM_TRANSCO' },
    CREATE_PARAM_TRANSCO_PENDING: { type: 'CREATE_PARAM_TRANSCO_PENDING' },
    CREATE_PARAM_TRANSCO_FULFILLED: { type: 'CREATE_PARAM_TRANSCO_FULFILLED' },

    EDIT_PARAM_TRANSCO: { type: 'EDIT_PARAM_TRANSCO' },
    EDIT_PARAM_TRANSCO_PENDING: { type: 'EDIT_PARAM_TRANSCO_PENDING' },
    EDIT_PARAM_TRANSCO_FULFILLED: { type: 'EDIT_PARAM_TRANSCO_FULFILLED' },

    DELETE_PARAM_TRANSCO: { type: 'DELETE_PARAM_TRANSCO' },

    GET_PARAM_TRANSCO_BY_CODE: { type: 'GET_PARAM_TRANSCO_BY_CODE' },
    GET_PARAM_TRANSCO_BY_CODE_PENDING: { type: 'GET_PARAM_TRANSCO_BY_CODE_PENDING' },
    GET_PARAM_TRANSCO_BY_CODE_FULFILLED: { type: 'GET_PARAM_TRANSCO_BY_CODE_FULFILLED' },

    // #################### SERVICES #############################
    GET_ALL_SERVICES_TRANSCO: { type: 'GET_ALL_SERVICES_TRANSCO' },
    GET_ALL_SERVICES_TRANSCO_PENDING: { type: 'GET_ALL_SERVICES_TRANSCO_PENDING' },
    GET_ALL_SERVICES_TRANSCO_FULFILLED: { type: 'GET_ALL_SERVICES_TRANSCO_FULFILLED' },

    CREATE_SERVICE_TRANSCO: { type: 'CREATE_SERVICE_TRANSCO' },
    CREATE_SERVICE_TRANSCO_PENDING: { type: 'CREATE_SERVICE_TRANSCO_PENDING' },
    CREATE_SERVICE_TRANSCO_FULFILLED: { type: 'CREATE_SERVICE_TRANSCO_FULFILLED' },

    DELETE_SERVICE_TRANSCO: { type: 'DELETE_SERVICE_TRANSCO' },

    UPDATE_SERVICE_TRANSCO: { type: 'UPDATE_SERVICE_TRANSCO' },
    UPDATE_SERVICE_TRANSCO_PENDING: { type: 'UPDATE_SERVICE_TRANSCO_PENDING' },
    UPDATE_SERVICE_TRANSCO_FULFILLED: { type: 'UPDATE_SERVICE_TRANSCO_FULFILLED' },

    // #################### AGREEMENT ##########################
    GET_ALL_AGREEMENT: { type: 'GET_ALL_AGREEMENT' },
    GET_ALL_AGREEMENT_PENDING: { type: 'GET_ALL_AGREEMENT_PENDING' },
    GET_ALL_AGREEMENT_FULFILLED: { type: 'GET_ALL_AGREEMENT_FULFILLED' },

    CREATE_AGREEMENT: { type: 'CREATE_AGREEMENT' },
    CREATE_AGREEMENT_PENDING: { type: 'CREATE_AGREEMENT_PENDING' },
    CREATE_AGREEMENT_FULFILLED: { type: 'CREATE_AGREEMENT_FULFILLED' },

    UPDATE_AGREEMENT: { type: 'CREATE_AGREEMENT' },
    UPDATE_AGREEMENT_PENDING: { type: 'CREATE_AGREEMENT_PENDING' },
    UPDATE_AGREEMENT_FULFILLED: { type: 'CREATE_AGREEMENT_FULFILLED' },

    DELETE_AGREEMENT: { type: 'DELETE_AGREEMENT' },
    DELETE_AGREEMENT_PENDING: { type: 'DELETE_AGREEMENT_PENDING' },
    DELETE_AGREEMENT_FULFILLED: { type: 'DELETE_AGREEMENT_FULFILLED' },

    // #################### SERVICE_METIER ##########################
    GET_ALL_SERVICE_METIER: { type: 'GET_ALL_SERVICE_METIER' },
    GET_ALL_SERVICE_METIER_PENDING: { type: 'GET_ALL_SERVICE_METIER_PENDING' },
    GET_ALL_SERVICE_METIER_FULFILLED: { type: 'GET_ALL_SERVICE_METIER_FULFILLED' },

    CREATE_SERVICE_METIER: { type: 'CREATE_SERVICE_METIER' },
    CREATE_SERVICE_METIER_PENDING: { type: 'CREATE_SERVICE_METIER_PENDING' },
    CREATE_SERVICE_METIER_FULFILLED: { type: 'CREATE_SERVICE_METIER_FULFILLED' },

    UPDATE_SERVICE_METIER: { type: 'CREATE_SERVICE_METIER' },
    UPDATE_SERVICE_METIER_PENDING: { type: 'CREATE_SERVICE_METIER_PENDING' },
    UPDATE_SERVICE_METIER_FULFILLED: { type: 'CREATE_SERVICE_METIER_FULFILLED' },

    DELETE_SERVICE_METIER: { type: 'DELETE_SERVICE_METIER' },
    DELETE_SERVICE_METIER_PENDING: { type: 'DELETE_SERVICE_METIER_PENDING' },
    DELETE_SERVICE_METIER_FULFILLED: { type: 'DELETE_SERVICE_METIER_FULFILLED' },

    // #################### PROCESS ##########################
    GET_ALL_PROCESS: { type: 'GET_ALL_PROCESS' },
    GET_ALL_PROCESS_PENDING: { type: 'GET_ALL_PROCESS_PENDING' },
    GET_ALL_PROCESS_FULFILLED: { type: 'GET_ALL_PROCESS_FULFILLED' },

    // #################### FILES TYPE ##########################
    GET_ALL_FILES_TYPE: { type: 'GET_ALL_FILES_TYPE' },
    GET_ALL_FILES_TYPE_PENDING: { type: 'GET_ALL_FILES_TYPE_PENDING' },
    GET_ALL_FILES_TYPE_FULFILLED: { type: 'GET_ALL_FILES_TYPE_FULFILLED' },

    // #################### REJECTS ##########################
    GET_ALL_REJECTS: { type: 'GET_ALL_REJECTS' },
    GET_ALL_REJECTS_PENDING: { type: 'GET_ALL_REJECTS_PENDING' },
    GET_ALL_REJECTS_FULFILLED: { type: 'GET_ALL_REJECTS_FULFILLED' },

    // #################### CLAIM ##########################
    GET_ALL_CLAIMS: { type: 'GET_ALL_CLAIMS' },
    GET_ALL_CLAIMS_PENDING: { type: 'GET_ALL_CLAIMS_PENDING' },
    GET_ALL_CLAIMS_FULFILLED: { type: 'GET_ALL_CLAIMS_FULFILLED' },

    CREATE_CLAIM: { type: 'CREATE_CLAIM' },
    CREATE_CLAIM_PENDING: { type: 'CREATE_CLAIM_PENDING' },
    CREATE_CLAIM_FULFILLED: { type: 'CREATE_CLAIM_FULFILLED' },

    UPDATE_CLAIM: { type: 'UPDATE_CLAIM' },
    UPDATE_CLAIM_PENDING: { type: 'UPDATE_CLAIM_PENDING' },
    UPDATE_CLAIM_FULFILLED: { type: 'UPDATE_CLAIM_FULFILLED' },

    DELETE_CLAIM: { type: 'DELETE_CLAIM' },
    DELETE_CLAIM_PENDING: { type: 'DELETE_CLAIM_PENDING' },
    DELETE_CLAIM_FULFILLED: { type: 'DELETE_CLAIM_FULFILLED' },

    // #################### DOMAIN ##########################
    GET_ALL_DOMAINS: { type: 'GET_ALL_DOMAINS' },
    GET_ALL_DOMAINS_PENDING: { type: 'GET_ALL_DOMAINS_PENDING' },
    GET_ALL_DOMAINS_FULFILLED: { type: 'GET_ALL_DOMAINS_FULFILLED' },

    CREATE_DOMAIN: { type: 'CREATE_DOMAIN' },
    CREATE_DOMAIN_PENDING: { type: 'CREATE_DOMAIN_PENDING' },
    CREATE_DOMAIN_FULFILLED: { type: 'CREATE_DOMAIN_FULFILLED' },

    UPDATE_DOMAIN: { type: 'UPDATE_DOMAIN' },
    UPDATE_DOMAIN_PENDING: { type: 'UPDATE_DOMAIN_PENDING' },
    UPDATE_DOMAIN_FULFILLED: { type: 'UPDATE_DOMAIN_FULFILLED' },

    DELETE_DOMAIN: { type: 'DELETE_DOMAIN' },
    DELETE_DOMAIN_PENDING: { type: 'DELETE_DOMAIN_PENDING' },
    DELETE_DOMAIN_FULFILLED: { type: 'DELETE_DOMAIN_FULFILLED' },

    // #################### ISANTE DOMAIN ##########################
    GET_ALL_DOMAINS_IS: { type: 'GET_ALL_DOMAINS_IS' },
    GET_ALL_DOMAINS_IS_PENDING: { type: 'GET_ALL_DOMAINS_IS_PENDING' },
    GET_ALL_DOMAINS_IS_FULFILLED: { type: 'GET_ALL_DOMAINS_IS_FULFILLED' },

    CREATE_DOMAIN_IS: { type: 'CREATE_DOMAIN_IS' },
    CREATE_DOMAIN_IS_PENDING: { type: 'CREATE_DOMAIN_IS_PENDING' },
    CREATE_DOMAIN_IS_FULFILLED: { type: 'CREATE_DOMAIN_IS_FULFILLED' },

    UPDATE_DOMAIN_IS: { type: 'UPDATE_DOMAIN_IS' },
    UPDATE_DOMAIN_IS_PENDING: { type: 'UPDATE_DOMAIN_IS_PENDING' },
    UPDATE_DOMAIN_IS_FULFILLED: { type: 'UPDATE_DOMAIN_IS_FULFILLED' },

    DELETE_DOMAIN_IS: { type: 'DELETE_DOMAIN_IS' },
    DELETE_DOMAIN_IS_PENDING: { type: 'DELETE_DOMAIN_IS_PENDING' },
    DELETE_DOMAIN_IS_FULFILLED: { type: 'DELETE_DOMAIN_IS_FULFILLED' },

    // #################### SP SANTE DOMAIN ##########################
    GET_ALL_DOMAINS_SP: { type: 'GET_ALL_DOMAINS_SP' },
    GET_ALL_DOMAINS_SP_PENDING: { type: 'GET_ALL_DOMAINS_SP_PENDING' },
    GET_ALL_DOMAINS_SP_FULFILLED: { type: 'GET_ALL_DOMAINS_SP_FULFILLED' },

    CREATE_DOMAIN_SP: { type: 'CREATE_DOMAIN_SP' },
    CREATE_DOMAIN_SP_PENDING: { type: 'CREATE_DOMAIN_SP_PENDING' },
    CREATE_DOMAIN_SP_FULFILLED: { type: 'CREATE_DOMAIN_SP_FULFILLED' },

    UPDATE_DOMAIN_SP: { type: 'UPDATE_DOMAIN_SP' },
    UPDATE_DOMAIN_SP_PENDING: { type: 'UPDATE_DOMAIN_SP_PENDING' },
    UPDATE_DOMAIN_SP_FULFILLED: { type: 'UPDATE_DOMAIN_SP_FULFILLED' },

    DELETE_DOMAIN_SP: { type: 'DELETE_DOMAIN_SP' },
    DELETE_DOMAIN_SP_PENDING: { type: 'DELETE_DOMAIN_SP_PENDING' },
    DELETE_DOMAIN_SP_FULFILLED: { type: 'DELETE_DOMAIN_SP_FULFILLED' },

    // #################### FORMULA ##########################
    GET_ALL_FORMULAS: { type: 'GET_ALL_FORMULAS' },
    GET_ALL_FORMULAS_PENDING: { type: 'GET_ALL_FORMULAS_PENDING' },
    GET_ALL_FORMULAS_FULFILLED: { type: 'GET_ALL_FORMULAS_FULFILLED' },

    CREATE_FORMULA: { type: 'CREATE_FORMULA' },
    CREATE_FORMULA_PENDING: { type: 'CREATE_FORMULA_PENDING' },
    CREATE_FORMULA_FULFILLED: { type: 'CREATE_FORMULA_FULFILLED' },

    UPDATE_FORMULA: { type: 'UPDATE_FORMULA' },
    UPDATE_FORMULA_PENDING: { type: 'UPDATE_FORMULA_PENDING' },
    UPDATE_FORMULA_FULFILLED: { type: 'UPDATE_FORMULA_FULFILLED' },

    DELETE_FORMULA: { type: 'DELETE_FORMULA' },
    DELETE_FORMULA_PENDING: { type: 'DELETE_FORMULA_PENDING' },
    DELETE_FORMULA_FULFILLED: { type: 'DELETE_FORMULA_FULFILLED' },

    // #################### RETURN CODES ##########################
    GET_ALL_RETURN_CODES: { type: 'GET_ALL_RETURN_CODES' },
    GET_ALL_RETURN_CODES_FULFILLED: { type: 'GET_ALL_RETURN_CODES_FULFILLED' },
};
