/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    SEARCH_ALMERYS_REFERENTIAL: { type: 'SEARCH_ALMERYS_REFERENTIAL' },
    SEARCH_ALMERYS_REFERENTIAL_PENDING: { type: 'SEARCH_ALMERYS_REFERENTIAL_PENDING' },
    SEARCH_ALMERYS_REFERENTIAL_FULFILLED: { type: 'SEARCH_ALMERYS_REFERENTIAL_FULFILLED' },

    CREATE_ALMERYS_PRODUCT: { type: 'CREATE_ALMERYS_PRODUCT' },
    CREATE_ALMERYS_PRODUCT_PENDING: { type: 'CREATE_ALMERYS_PRODUCT_PENDING' },
    CREATE_ALMERYS_PRODUCT_FULFILLED: { type: 'SEARCH_ALMERYS_REFERENTIAL_FULFILLED' },

    UPDATE_ALMERYS_PRODUCT: { type: 'UPDATE_ALMERYS_PRODUCT' },
    UPDATE_ALMERYS_PRODUCT_PENDING: { type: 'UPDATE_ALMERYS_PRODUCT_PENDING' },
    UPDATE_ALMERYS_PRODUCT_FULFILLED: { type: 'UPDATE_ALMERYS_PRODUCT_FULFILLED' },

    SEARCH_ALMERYS_PRODUCT: { type: 'SEARCH_ALMERYS_PRODUCT' },
    SEARCH_ALMERYS_PRODUCT_PENDING: { type: 'SEARCH_ALMERYS_PRODUCT_PENDING' },
    SEARCH_ALMERYS_PRODUCT_FULFILLED: { type: 'SEARCH_ALMERYS_PRODUCT_FULFILLED' },
};
