/** Please modify this class to meet your needs This class is not complete */
package com.cegedimassurance.ws.annulationaccreditation.wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:55.416+01:00 Generated source
 * version: 3.1.13
 */
@jakarta.jws.WebService(
    serviceName = "WSannulationAccreditationWSDL",
    portName = "WSAnnulationAccreditation",
    targetNamespace = "http://ws.cegedimassurance.com/annulationaccreditation/wsdl",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/annulation_accreditation.wsdl",
    endpointInterface =
        "com.cegedimassurance.ws.annulationaccreditation.wsdl.WSAnnulationAccreditation")
public class WSAnnulationAccreditationImpl implements WSAnnulationAccreditation {

  private static final Logger LOG = Logger.getLogger(WSAnnulationAccreditationImpl.class.getName());

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.annulationaccreditation.wsdl.
   * WSAnnulationAccreditation#getannulation(com.cegedimassurances.norme.
   * annulation_accreditation.GetAnnulationAccreditationIn parameters)*
   */
  public com.cegedimassurances.norme.annulation_accreditation.GetAnnulationAccreditationOut
      getannulation(
          com.cegedimassurances.norme.annulation_accreditation.GetAnnulationAccreditationIn
              parameters) {
    LOG.info("Executing operation getannulation");
    System.out.println(parameters);
    try {
      com.cegedimassurances.norme.annulation_accreditation.GetAnnulationAccreditationOut _return =
          null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }
}
