package com.cegedimassurance.ws.annulationaccreditation.wsdl;

/** Please modify this class to meet your needs This class is not complete */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:55.404+01:00 Generated source
 * version: 3.1.13
 */
public final class WSAnnulationAccreditation_WSAnnulationAccreditation_Client {

  private static final QName SERVICE_NAME =
      new QName(
          "http://ws.cegedimassurance.com/annulationaccreditation/wsdl",
          "WSannulationAccreditationWSDL");

  private WSAnnulationAccreditation_WSAnnulationAccreditation_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = WSannulationAccreditationWSDL.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    WSannulationAccreditationWSDL ss = new WSannulationAccreditationWSDL(wsdlURL, SERVICE_NAME);
    WSAnnulationAccreditation port = ss.getWSAnnulationAccreditation();

    {
      System.out.println("Invoking getannulation...");
      com.cegedimassurances.norme.annulation_accreditation.GetAnnulationAccreditationIn
          _getannulation_parameters = null;
      com.cegedimassurances.norme.annulation_accreditation.GetAnnulationAccreditationOut
          _getannulation__return = port.getannulation(_getannulation_parameters);
      System.out.println("getannulation.result=" + _getannulation__return);
    }

    System.exit(0);
  }
}
