package com.cegedimassurance.ws.annulationaccreditation.wsdl;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:55.440+01:00 Generated source
 * version: 3.1.13
 */
@WebServiceClient(
    name = "WSannulationAccreditationWSDL",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/annulation_accreditation.wsdl",
    targetNamespace = "http://ws.cegedimassurance.com/annulationaccreditation/wsdl")
public class WSannulationAccreditationWSDL extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName(
          "http://ws.cegedimassurance.com/annulationaccreditation/wsdl",
          "WSannulationAccreditationWSDL");
  public static final QName WSAnnulationAccreditation =
      new QName(
          "http://ws.cegedimassurance.com/annulationaccreditation/wsdl",
          "WSAnnulationAccreditation");

  static {
    URL url = null;
    try {
      url =
          new URL(
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/annulation_accreditation.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(WSannulationAccreditationWSDL.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/annulation_accreditation.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public WSannulationAccreditationWSDL(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public WSannulationAccreditationWSDL(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public WSannulationAccreditationWSDL() {
    super(WSDL_LOCATION, SERVICE);
  }

  /**
   * @return returns WSAnnulationAccreditation
   */
  @WebEndpoint(name = "WSAnnulationAccreditation")
  public WSAnnulationAccreditation getWSAnnulationAccreditation() {
    return super.getPort(WSAnnulationAccreditation, WSAnnulationAccreditation.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns WSAnnulationAccreditation
   */
  @WebEndpoint(name = "WSAnnulationAccreditation")
  public WSAnnulationAccreditation getWSAnnulationAccreditation(WebServiceFeature... features) {
    return super.getPort(WSAnnulationAccreditation, WSAnnulationAccreditation.class, features);
  }
}
