package com.cegedimassurance.ws.annulationaccreditation.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:55.425+01:00 Generated source
 * version: 3.1.13
 */
@WebService(
    targetNamespace = "http://ws.cegedimassurance.com/annulationaccreditation/wsdl",
    name = "WSAnnulationAccreditation")
@XmlSeeAlso({
  com.cegedimassurances.norme.commun.ObjectFactory.class,
  com.cegedimassurances.norme.annulation_accreditation.ObjectFactory.class,
  ObjectFactory.class
})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WSAnnulationAccreditation {

  @WebMethod(action = "http://ws.fsiq.com/annulationaccreditation/getannulation")
  @WebResult(
      name = "PECannulee",
      targetNamespace = "http://ws.cegedimassurance.com/annulationaccreditation/wsdl",
      partName = "parameters")
  public com.cegedimassurances.norme.annulation_accreditation.GetAnnulationAccreditationOut
      getannulation(
          @WebParam(
                  partName = "parameters",
                  name = "annulePEC",
                  targetNamespace = "http://ws.cegedimassurance.com/annulationaccreditation/wsdl")
              com.cegedimassurances.norme.annulation_accreditation.GetAnnulationAccreditationIn
                  parameters);
}
