package com.cegedimassurance.ws.servicesps.wsdl;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:54.808+01:00 Generated source
 * version: 3.1.13
 */
@WebServiceClient(
    name = "FSIQServicesPS",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_ps.wsdl",
    targetNamespace = "http://ws.cegedimassurance.com/servicesps/wsdl")
public class FSIQServicesPS extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName("http://ws.cegedimassurance.com/servicesps/wsdl", "FSIQServicesPS");
  public static final QName ServicesPSPort =
      new QName("http://ws.cegedimassurance.com/servicesps/wsdl", "ServicesPSPort");

  static {
    URL url = null;
    try {
      url =
          new URL(
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_ps.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(FSIQServicesPS.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_ps.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public FSIQServicesPS(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public FSIQServicesPS(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public FSIQServicesPS() {
    super(WSDL_LOCATION, SERVICE);
  }

  /**
   * @return returns ServicesPS
   */
  @WebEndpoint(name = "ServicesPSPort")
  public ServicesPS getServicesPSPort() {
    return super.getPort(ServicesPSPort, ServicesPS.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns ServicesPS
   */
  @WebEndpoint(name = "ServicesPSPort")
  public ServicesPS getServicesPSPort(WebServiceFeature... features) {
    return super.getPort(ServicesPSPort, ServicesPS.class, features);
  }
}
