package com.cegedimassurance.ws.servicesps.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:54.802+01:00 Generated source
 * version: 3.1.13
 */
@WebService(targetNamespace = "http://ws.cegedimassurance.com/servicesps/wsdl", name = "ServicesPS")
@XmlSeeAlso({
  com.cegedimassurances.norme.abonnement.ObjectFactory.class,
  com.cegedimassurances.norme.amc.ObjectFactory.class,
  com.cegedimassurances.norme.beneficiaire.ObjectFactory.class,
  com.cegedimassurances.norme.commun.ObjectFactory.class,
  com.cegedimassurances.norme.carte.ObjectFactory.class,
  com.cegedimassurances.norme.ps.ObjectFactory.class
})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicesPS {

  /** Obtention des données permettant la construction de la carte */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicesps/wsdl/getCarteTPData")
  @WebResult(name = "reponse_carteTP", targetNamespace = "", partName = "reponse_carteTP")
  public com.cegedimassurances.norme.carte.ReponseCarteTP getCarteTPData(
      @WebParam(partName = "requete_ps", name = "requete_ps", targetNamespace = "")
          com.cegedimassurances.norme.ps.RequetePs requetePs);

  /** Appel de l'abonnement ps */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicesps/wsdl/getServicesOuverts")
  @WebResult(name = "reponse_abonnement", targetNamespace = "", partName = "reponse_abonnement")
  public com.cegedimassurances.norme.abonnement.ReponseAbonnement getServicesOuverts(
      @WebParam(partName = "requete_ps", name = "requete_ps", targetNamespace = "")
          com.cegedimassurances.norme.ps.RequetePs requetePs);
}
