/** Please modify this class to meet your needs This class is not complete */
package com.cegedimassurance.ws.servicesps.wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:54.793+01:00 Generated source
 * version: 3.1.13
 */
@jakarta.jws.WebService(
    serviceName = "FSIQServicesPS",
    portName = "ServicesPSPort",
    targetNamespace = "http://ws.cegedimassurance.com/servicesps/wsdl",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_ps.wsdl",
    endpointInterface = "com.cegedimassurance.ws.servicesps.wsdl.ServicesPS")
public class ServicesPSPortImpl implements ServicesPS {

  private static final Logger LOG = Logger.getLogger(ServicesPSPortImpl.class.getName());

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.servicesps.wsdl.ServicesPS#getCarteTPData(com.
   * cegedimassurances.norme.ps.RequetePs requetePs)*
   */
  public com.cegedimassurances.norme.carte.ReponseCarteTP getCarteTPData(
      com.cegedimassurances.norme.ps.RequetePs requetePs) {
    LOG.info("Executing operation getCarteTPData");
    System.out.println(requetePs);
    try {
      com.cegedimassurances.norme.carte.ReponseCarteTP _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   *
   * @see
   * com.cegedimassurance.ws.servicesps.wsdl.ServicesPS#getServicesOuverts(com.
   * cegedimassurances.norme.ps.RequetePs requetePs)*
   */
  public com.cegedimassurances.norme.abonnement.ReponseAbonnement getServicesOuverts(
      com.cegedimassurances.norme.ps.RequetePs requetePs) {
    LOG.info("Executing operation getServicesOuverts");
    System.out.println(requetePs);
    try {
      com.cegedimassurances.norme.abonnement.ReponseAbonnement _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }
}
