package com.cegedimassurance.ws.servicesps.wsdl;

/** Please modify this class to meet your needs This class is not complete */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:36:54.782+01:00 Generated source
 * version: 3.1.13
 */
public final class ServicesPS_ServicesPSPort_Client {

  private static final QName SERVICE_NAME =
      new QName("http://ws.cegedimassurance.com/servicesps/wsdl", "FSIQServicesPS");

  private ServicesPS_ServicesPSPort_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = FSIQServicesPS.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    FSIQServicesPS ss = new FSIQServicesPS(wsdlURL, SERVICE_NAME);
    ServicesPS port = ss.getServicesPSPort();

    {
      System.out.println("Invoking getCarteTPData...");
      com.cegedimassurances.norme.ps.RequetePs _getCarteTPData_requetePs = null;
      com.cegedimassurances.norme.carte.ReponseCarteTP _getCarteTPData__return =
          port.getCarteTPData(_getCarteTPData_requetePs);
      System.out.println("getCarteTPData.result=" + _getCarteTPData__return);
    }
    {
      System.out.println("Invoking getServicesOuverts...");
      com.cegedimassurances.norme.ps.RequetePs _getServicesOuverts_requetePs = null;
      com.cegedimassurances.norme.abonnement.ReponseAbonnement _getServicesOuverts__return =
          port.getServicesOuverts(_getServicesOuverts_requetePs);
      System.out.println("getServicesOuverts.result=" + _getServicesOuverts__return);
    }

    System.exit(0);
  }
}
