/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    GET_ALL_TRANSCODAGE_SERVICE: { type: 'GET_ALL_TRANSCODAGE_SERVICE' },
    GET_ALL_TRANSCODAGE_SERVICE_PENDING: { type: 'GET_ALL_TRANSCODAGE_SERVICE_PENDING' },
    GET_ALL_TRANSCODAGE_SERVICE_FULFILLED: { type: 'GET_ALL_TRANSCODAGE_SERVICE_FULFILLED' },

    GET_TRANSCO_MAPPING: { type: 'GET_TRANSCO_MAPPING' },
    GET_TRANSCO_MAPPING_PENDING: { type: 'GET_TRANSCO_MAPPING_PENDING' },
    GET_TRANSCO_MAPPING_FULFILLED: { type: 'GET_TRANSCO_MAPPING_FULFILLED' },

    UPDATE_TRANSCO_MAPPING: { type: 'UPDATE_TRANSCO_MAPPING' },
    UPDATE_TRANSCO_MAPPING_PENDING: { type: 'UPDATE_TRANSCO_MAPPING_PENDING' },
    UPDATE_TRANSCO_MAPPING_FULFILLED: { type: 'UPDATE_TRANSCO_MAPPING_FULFILLED' },
};
