export default {
    FORM_NAME: 'declarantForm',
    FIELDS: {
        amcNumber: 'amcNumber',
        amcLabel: 'amcLabel',
        couloir: 'couloir',
        service: 'service',
        clientId: 'idClientBO',
    },
    REGROUPEMENT_MANDATORY_FIELDS: {
        dateOuverture: 'dateOuverture',
        couloirClient: 'couloirClient',
        numEmetteur: 'numEmetteur',
        numDebutFichier: 'numDebutFichier',
        numClient: 'numClient',
        nomClient: 'nomClient',
        versionNorme: 'versionNorme',
        typeFichier: 'typeFichier',
        codePerimetre: 'codePerimetre',
        nomPerimetre: 'nomPerimetre',
        typeGestionnaireBO: 'typeGestionnaireBO',
        libelleGestionnaireBO: 'libelleGestionnaireBO',
        codeClient: 'codeClient',
        numExterneContratIndividuel: 'numExterneContratIndividuel',
        numExterneContratCollectif: 'numExterneContratCollectif',
    },
    SERVICES: [
        { id: 'PRIORISATION', nom: 'PRIORISATION' },
        { id: 'VISIODROIT', nom: 'VISIODROIT' },
        { id: 'DCLBENIS', nom: 'DCLBEN-IS' },
        { id: 'DCLBENSP', nom: 'DCLBEN-SP' },
        { id: 'TPGIS', nom: 'TPG-IS' },
        { id: 'TPGSP', nom: 'TPG-SP' },
        { id: 'ALMV3', nom: 'ALMV3' },
        { id: 'CARTETP', nom: 'CARTE-TP' },
        { id: 'CARTEDEMATERIALISEE', nom: 'CARTE-DEMATERIALISEE' },
        { id: 'SELROC', nom: 'SEL-ROC' },
        { id: 'SELTP', nom: 'SEL-TP' },
    ],
};
