/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    GET_ONE_DECLARANT: { type: 'GET_ONE_DECLARANT' },
    GET_ONE_DECLARANT_PENDING: { type: 'GET_ONE_DECLARANT_PENDING' },
    GET_ONE_DECLARANT_FULFILLED: { type: 'GET_ONE_DECLARANT_FULFILLED' },
    GET_ONE_DECLARANT_REJECTED: { type: 'GET_ONE_DECLARANT_REJECTED' },

    CREATE_DECLARANT: { type: 'CREATE_DECLARANT' },
    CREATE_DECLARANT_PENDING: { type: 'CREATE_DECLARANT_PENDING' },
    CREATE_DECLARANT_FULFILLED: { type: 'CREATE_DECLARANT_FULFILLED' },
    CREATE_DECLARANT_REJECTED: { type: 'CREATE_DECLARANT_REJECTED' },

    UPDATE_DECLARANT: { type: 'UPDATE_DECLARANT' },
    UPDATE_DECLARANT_PENDING: { type: 'UPDATE_DECLARANT_PENDING' },
    UPDATE_DECLARANT_FULFILLED: { type: 'UPDATE_DECLARANT_FULFILLED' },
    UPDATE_DECLARANT_REJECTED: { type: 'UPDATE_DECLARANT_REJECTED' },

    EXISTS_DECLARANT: { type: 'EXISTS_DECLARANT' },

    GET_DOMAINES_TP: { type: 'GET_DOMAINES_TP' },
    GET_DOMAINES_TP_PENDING: { type: 'GET_DOMAINES_TP_PENDING' },
    GET_DOMAINES_TP_FULFILLED: { type: 'GET_DOMAINES_TP_FULFILLED' },
    GET_DOMAINES_TP_REJECTED: { type: 'GET_DOMAINES_TP_REJECTED' },

    GET_RESEAUX_SOIN: { type: 'GET_RESEAUX_SOIN' },
    GET_RESEAUX_SOIN_PENDING: { type: 'GET_RESEAUX_SOIN_PENDING' },
    GET_RESEAUX_SOIN_FULFILLED: { type: 'GET_RESEAUX_SOIN_FULFILLED' },
    GET_RESEAUX_SOIN_REJECTED: { type: 'GET_RESEAUX_SOIN_REJECTED' },
};
