package com.cegedimassurance.ws.servicestarification.wsdl;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:01.030+01:00 Generated source
 * version: 3.1.13
 */
@WebServiceClient(
    name = "FSIQServicesTarification",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_tarification.wsdl",
    targetNamespace = "http://ws.cegedimassurance.com/servicestarification/wsdl")
public class FSIQServicesTarification extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName(
          "http://ws.cegedimassurance.com/servicestarification/wsdl", "FSIQServicesTarification");
  public static final QName ServicesTarificationPort =
      new QName(
          "http://ws.cegedimassurance.com/servicestarification/wsdl", "ServicesTarificationPort");

  static {
    URL url = null;
    try {
      url =
          new URL(
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_tarification.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(FSIQServicesTarification.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_tarification.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public FSIQServicesTarification(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public FSIQServicesTarification(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public FSIQServicesTarification() {
    super(WSDL_LOCATION, SERVICE);
  }

  /**
   * @return returns ServicesTarification
   */
  @WebEndpoint(name = "ServicesTarificationPort")
  public ServicesTarification getServicesTarificationPort() {
    return super.getPort(ServicesTarificationPort, ServicesTarification.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns ServicesTarification
   */
  @WebEndpoint(name = "ServicesTarificationPort")
  public ServicesTarification getServicesTarificationPort(WebServiceFeature... features) {
    return super.getPort(ServicesTarificationPort, ServicesTarification.class, features);
  }
}
