package com.cegedimassurance.ws.servicestarification.wsdl;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:03.912+01:00 Generated source
 * version: 3.1.13
 */
@WebServiceClient(
    name = "FSIQServicesJustificationCalcul",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_justification_calcul.wsdl",
    targetNamespace = "http://ws.cegedimassurance.com/servicestarification/wsdl")
public class FSIQServicesJustificationCalcul extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName(
          "http://ws.cegedimassurance.com/servicestarification/wsdl",
          "FSIQServicesJustificationCalcul");
  public static final QName ServicesJustificationCalculPort =
      new QName(
          "http://ws.cegedimassurance.com/servicestarification/wsdl",
          "ServicesJustificationCalculPort");

  static {
    URL url = null;
    try {
      url =
          new URL(
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_justification_calcul.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(FSIQServicesJustificationCalcul.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_justification_calcul.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public FSIQServicesJustificationCalcul(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public FSIQServicesJustificationCalcul(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public FSIQServicesJustificationCalcul() {
    super(WSDL_LOCATION, SERVICE);
  }

  /**
   * @return returns ServicesJustificationCalcul
   */
  @WebEndpoint(name = "ServicesJustificationCalculPort")
  public ServicesJustificationCalcul getServicesJustificationCalculPort() {
    return super.getPort(ServicesJustificationCalculPort, ServicesJustificationCalcul.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns ServicesJustificationCalcul
   */
  @WebEndpoint(name = "ServicesJustificationCalculPort")
  public ServicesJustificationCalcul getServicesJustificationCalculPort(
      WebServiceFeature... features) {
    return super.getPort(
        ServicesJustificationCalculPort, ServicesJustificationCalcul.class, features);
  }
}
