package com.cegedimassurance.ws.servicestarification.wsdl;

/** Please modify this class to meet your needs This class is not complete */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:03.878+01:00 Generated source
 * version: 3.1.13
 */
public final class ServicesJustificationCalcul_ServicesJustificationCalculPort_Client {

  private static final QName SERVICE_NAME =
      new QName(
          "http://ws.cegedimassurance.com/servicestarification/wsdl",
          "FSIQServicesJustificationCalcul");

  private ServicesJustificationCalcul_ServicesJustificationCalculPort_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = FSIQServicesJustificationCalcul.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    FSIQServicesJustificationCalcul ss = new FSIQServicesJustificationCalcul(wsdlURL, SERVICE_NAME);
    ServicesJustificationCalcul port = ss.getServicesJustificationCalculPort();

    {
      System.out.println("Invoking getJustifCalcul...");
      com.cegedimassurances.norme.tarification.RequeteJustificationCalcul
          _getJustifCalcul_requeteJustificationCalcul = null;
      com.cegedimassurances.norme.tarification.ReponseJustificationCalcul _getJustifCalcul__return =
          port.getJustifCalcul(_getJustifCalcul_requeteJustificationCalcul);
      System.out.println("getJustifCalcul.result=" + _getJustifCalcul__return);
    }

    System.exit(0);
  }
}
