package com.cegedimassurance.ws.servicestarification.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:01.023+01:00 Generated source
 * version: 3.1.13
 */
@WebService(
    targetNamespace = "http://ws.cegedimassurance.com/servicestarification/wsdl",
    name = "ServicesTarification")
@XmlSeeAlso({
  com.cegedimassurances.norme.tarification.ObjectFactory.class,
  com.cegedimassurances.norme.commun.ObjectFactory.class,
  com.cegedimassurances.norme.base_de_droit.ObjectFactory.class,
  com.cegedimassurances.norme.ps.ObjectFactory.class
})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicesTarification {

  /** Appel du service d'annulation de la prise en charge. */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicestarification/wsdl/annulePec")
  @WebResult(
      name = "reponse_annulation_pec",
      targetNamespace = "",
      partName = "reponse_annulation_pec")
  public com.cegedimassurances.norme.tarification.ReponseAnnulationPec annulePec(
      @WebParam(
              partName = "requete_annulation_pec",
              name = "requete_annulation_pec",
              targetNamespace = "")
          com.cegedimassurances.norme.tarification.RequeteAnnulationPec requeteAnnulationPec);

  /** Appel du service de devis de la tarification */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicestarification/wsdl/getDevis")
  @WebResult(name = "reponse_tarification", targetNamespace = "", partName = "reponse_tarification")
  public com.cegedimassurances.norme.tarification.ReponseTarification getDevis(
      @WebParam(
              partName = "requete_tarification",
              name = "requete_tarification",
              targetNamespace = "")
          com.cegedimassurances.norme.tarification.RequeteTarification requeteTarification);

  /**
   * Appel du service prise en charge de la tarification. Dans le header de la réponse doit être
   * renseigné le numéro d'accréditation.
   */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicestarification/wsdl/getPec")
  @WebResult(name = "reponse_tarification", targetNamespace = "", partName = "reponse_tarification")
  public com.cegedimassurances.norme.tarification.ReponseTarification getPec(
      @WebParam(
              partName = "requete_tarification",
              name = "requete_tarification",
              targetNamespace = "")
          com.cegedimassurances.norme.tarification.RequeteTarification requeteTarification);
}
