package com.cegedimassurance.ws.servicestarification.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:03.889+01:00 Generated source
 * version: 3.1.13
 */
@WebService(
    targetNamespace = "http://ws.cegedimassurance.com/servicestarification/wsdl",
    name = "ServicesJustificationCalcul")
@XmlSeeAlso({
  com.cegedimassurances.norme.tarification.ObjectFactory.class,
  com.cegedimassurances.norme.commun.ObjectFactory.class
})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicesJustificationCalcul {

  /** Appel du service justification du calcul. */
  @WebMethod(action = "http://ws.cegedimassurance.com/servicestarification/wsdl/getJustifCalcul")
  @WebResult(
      name = "reponse_justification_calcul",
      targetNamespace = "",
      partName = "reponse_justification_calcul")
  public com.cegedimassurances.norme.tarification.ReponseJustificationCalcul getJustifCalcul(
      @WebParam(
              partName = "requete_justification_calcul",
              name = "requete_justification_calcul",
              targetNamespace = "")
          com.cegedimassurances.norme.tarification.RequeteJustificationCalcul
              requeteJustificationCalcul);
}
