/** Please modify this class to meet your needs This class is not complete */
package com.cegedimassurance.ws.servicestarification.wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:03.883+01:00 Generated source
 * version: 3.1.13
 */
@jakarta.jws.WebService(
    serviceName = "FSIQServicesJustificationCalcul",
    portName = "ServicesJustificationCalculPort",
    targetNamespace = "http://ws.cegedimassurance.com/servicestarification/wsdl",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_justification_calcul.wsdl",
    endpointInterface =
        "com.cegedimassurance.ws.servicestarification.wsdl.ServicesJustificationCalcul")
public class ServicesJustificationCalculPortImpl implements ServicesJustificationCalcul {

  private static final Logger LOG =
      Logger.getLogger(ServicesJustificationCalculPortImpl.class.getName());

  /*
   * (non-Javadoc)
   *
   * @see
   * com.cegedimassurance.ws.servicestarification.wsdl.ServicesJustificationCalcul
   * #getJustifCalcul(com.cegedimassurances.norme.tarification.
   * RequeteJustificationCalcul requeteJustificationCalcul)*
   */
  public com.cegedimassurances.norme.tarification.ReponseJustificationCalcul getJustifCalcul(
      com.cegedimassurances.norme.tarification.RequeteJustificationCalcul
          requeteJustificationCalcul) {
    LOG.info("Executing operation getJustifCalcul");
    System.out.println(requeteJustificationCalcul);
    try {
      com.cegedimassurances.norme.tarification.ReponseJustificationCalcul _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }
}
