/** Please modify this class to meet your needs This class is not complete */
package com.cegedimassurance.ws.servicestarification.wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:01.006+01:00 Generated source
 * version: 3.1.13
 */
@jakarta.jws.WebService(
    serviceName = "FSIQServicesTarification",
    portName = "ServicesTarificationPort",
    targetNamespace = "http://ws.cegedimassurance.com/servicestarification/wsdl",
    wsdlLocation =
        "file:/C:/dev/BDD2/bdd-soap-schema/./normes-cegedim-assurance/src/main/resources/wsdl/fsiq_services_tarification.wsdl",
    endpointInterface = "com.cegedimassurance.ws.servicestarification.wsdl.ServicesTarification")
public class ServicesTarificationPortImpl implements ServicesTarification {

  private static final Logger LOG = Logger.getLogger(ServicesTarificationPortImpl.class.getName());

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.servicestarification.wsdl.ServicesTarification#
   * annulePec(com.cegedimassurances.norme.tarification.RequeteAnnulationPec
   * requeteAnnulationPec)*
   */
  public com.cegedimassurances.norme.tarification.ReponseAnnulationPec annulePec(
      com.cegedimassurances.norme.tarification.RequeteAnnulationPec requeteAnnulationPec) {
    LOG.info("Executing operation annulePec");
    System.out.println(requeteAnnulationPec);
    try {
      com.cegedimassurances.norme.tarification.ReponseAnnulationPec _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   *
   * @see com.cegedimassurance.ws.servicestarification.wsdl.ServicesTarification#
   * getDevis(com.cegedimassurances.norme.tarification.RequeteTarification
   * requeteTarification)*
   */
  public com.cegedimassurances.norme.tarification.ReponseTarification getDevis(
      com.cegedimassurances.norme.tarification.RequeteTarification requeteTarification) {
    LOG.info("Executing operation getDevis");
    System.out.println(requeteTarification);
    try {
      com.cegedimassurances.norme.tarification.ReponseTarification _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   *
   * @see
   * com.cegedimassurance.ws.servicestarification.wsdl.ServicesTarification#getPec
   * (com.cegedimassurances.norme.tarification.RequeteTarification
   * requeteTarification)*
   */
  public com.cegedimassurances.norme.tarification.ReponseTarification getPec(
      com.cegedimassurances.norme.tarification.RequeteTarification requeteTarification) {
    LOG.info("Executing operation getPec");
    System.out.println(requeteTarification);
    try {
      com.cegedimassurances.norme.tarification.ReponseTarification _return = null;
      return _return;
    } catch (java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }
}
