package com.cegedimassurance.ws.servicestarification.wsdl;

/** Please modify this class to meet your needs This class is not complete */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.13 2021-03-19T16:37:00.993+01:00 Generated source
 * version: 3.1.13
 */
public final class ServicesTarification_ServicesTarificationPort_Client {

  private static final QName SERVICE_NAME =
      new QName(
          "http://ws.cegedimassurance.com/servicestarification/wsdl", "FSIQServicesTarification");

  private ServicesTarification_ServicesTarificationPort_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = FSIQServicesTarification.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    FSIQServicesTarification ss = new FSIQServicesTarification(wsdlURL, SERVICE_NAME);
    ServicesTarification port = ss.getServicesTarificationPort();

    {
      System.out.println("Invoking annulePec...");
      com.cegedimassurances.norme.tarification.RequeteAnnulationPec
          _annulePec_requeteAnnulationPec = null;
      com.cegedimassurances.norme.tarification.ReponseAnnulationPec _annulePec__return =
          port.annulePec(_annulePec_requeteAnnulationPec);
      System.out.println("annulePec.result=" + _annulePec__return);
    }
    {
      System.out.println("Invoking getDevis...");
      com.cegedimassurances.norme.tarification.RequeteTarification _getDevis_requeteTarification =
          null;
      com.cegedimassurances.norme.tarification.ReponseTarification _getDevis__return =
          port.getDevis(_getDevis_requeteTarification);
      System.out.println("getDevis.result=" + _getDevis__return);
    }
    {
      System.out.println("Invoking getPec...");
      com.cegedimassurances.norme.tarification.RequeteTarification _getPec_requeteTarification =
          null;
      com.cegedimassurances.norme.tarification.ReponseTarification _getPec__return =
          port.getPec(_getPec_requeteTarification);
      System.out.println("getPec.result=" + _getPec__return);
    }

    System.exit(0);
  }
}
