/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    GET_ALL_PROCESSUS: { type: 'GET_ALL_PROCESSUS' },
    GET_ALL_PROCESSUS_PENDING: { type: 'GET_ALL_PROCESSUS_PENDING' },
    GET_ALL_PROCESSUS_FULFILLED: { type: 'GET_ALL_PROCESSUS_FULFILLED' },
    GET_ALL_PROCESSUS_REJECTED: { type: 'GET_ALL_PROCESSUS_REJECTED' },

    GET_ALL_TYPE_FILE: { type: 'GET_ALL_TYPE_FILE' },
    GET_ALL_TYPE_FILE_PENDING: { type: 'GET_ALL_TYPE_FILE_PENDING' },
    GET_ALL_TYPE_FILE_FULFILLED: { type: 'GET_ALL_TYPE_FILE_FULFILLED' },
    GET_ALL_TYPE_FILE_REJECTED: { type: 'GET_ALL_TYPE_FILE_REJECTED' },

    GET_SENT_FLUX: { type: 'GET_SENT_FLUX' },
    GET_SENT_FLUX_PENDING: { type: 'GET_SENT_FLUX_PENDING' },
    GET_SENT_FLUX_FULFILLED: { type: 'GET_SENT_FLUX_FULFILLED' },
    GET_SENT_FLUX_REJECTED: { type: 'GET_SENT_FLUX_REJECTED' },

    GET_RECEIVED_FLUX: { type: 'GET_RECEIVED_FLUX' },
    GET_RECEIVED_FLUX_PENDING: { type: 'GET_RECEIVED_FLUX_PENDING' },
    GET_RECEIVED_FLUX_FULFILLED: { type: 'GET_RECEIVED_FLUX_FULFILLED' },
    GET_RECEIVED_FLUX_REJECTED: { type: 'GET_RECEIVED_FLUX_REJECTED' },

    FLUX_SENT_PAGING: { type: 'FLUX_SENT_PAGING' },
    FLUX_RECEIVED_PAGING: { type: 'FLUX_RECEIVED_PAGING' },
};
