/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    GET_NEXT_CONSOLIDATED_CONTRACT_TP: { type: 'GET_NEXT_CONSOLIDATED_CONTRACT_TP' },
    GET_NEXT_CONSOLIDATED_CONTRACT_TP_PENDING: { type: 'GET_NEXT_CONSOLIDATED_CONTRACT_TP_PENDING' },
    GET_NEXT_CONSOLIDATED_CONTRACT_TP_FULFILLED: { type: 'GET_NEXT_CONSOLIDATED_CONTRACT_TP_FULFILLED' },
    GET_NEXT_CONSOLIDATED_CONTRACT_TP_REJECTED: { type: 'GET_NEXT_CONSOLIDATED_CONTRACT_TP_REJECTED' },
    GET_NEXT_CERTIFICATIONS: { type: 'GET_NEXT_CERTIFICATIONS' },
    GET_NEXT_CERTIFICATIONS_PENDING: { type: 'GET_NEXT_CERTIFICATIONS_PENDING' },
    GET_NEXT_CERTIFICATIONS_FULFILLED: { type: 'GET_NEXT_CERTIFICATIONS_FULFILLED' },
    GET_NEXT_CERTIFICATIONS_REJECTED: { type: 'GET_NEXT_CERTIFICATIONS_REJECTED' },

    GET_NEXT_DECLARATIONS: { type: 'GET_NEXT_DECLARATIONS' },
    GET_NEXT_DECLARATIONS_PENDING: { type: 'GET_NEXT_DECLARATIONS_PENDING' },
    GET_NEXT_DECLARATIONS_FULFILLED: { type: 'GET_NEXT_DECLARATIONS_FULFILLED' },
    GET_NEXT_DECLARATIONS_REJECTED: { type: 'GET_NEXT_DECLARATIONS_REJECTED' },
};
