/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    SEARCH_BENEFICIARY: { type: 'SEARCH_BENEFICIARY' },
    SEARCH_BENEFICIARY_PENDING: { type: 'SEARCH_BENEFICIARY_PENDING' },
    SEARCH_BENEFICIARY_FULFILLED: { type: 'SEARCH_BENEFICIARY_FULFILLED' },
    SEARCH_BENEFICIARY_REJECTED: { type: 'SEARCH_BENEFICIARY_REJECTED' },

    GET_ALL_NAME: { type: 'GET_ALL_NAME' },
    GET_ALL_NAME_PENDING: { type: 'GET_ALL_NAME_PENDING' },
    GET_ALL_NAME_FULFILLED: { type: 'GET_ALL_NAME_FULFILLED' },
    GET_ALL_NAME_REJECTED: { type: 'GET_ALL_NAME_REJECTED' },

    GET_ALL_FIRSTNAME: { type: 'GET_ALL_FIRSTNAME' },
    GET_ALL_FIRSTNAME_PENDING: { type: 'GET_ALL_FIRSTNAME_PENDING' },
    GET_ALL_FIRSTNAME_FULFILLED: { type: 'GET_ALL_FIRSTNAME_FULFILLED' },
    GET_ALL_FIRSTNAME_REJECTED: { type: 'GET_ALL_FIRSTNAME_REJECTED' },

    GET_ALL_NIR: { type: 'GET_ALL_NIR' },
    GET_ALL_NIR_PENDING: { type: 'GET_ALL_NIR_PENDING' },
    GET_ALL_NIR_FULFILLED: { type: 'GET_ALL_NIR_FULFILLED' },
    GET_ALL_NIR_REJECTED: { type: 'GET_ALL_NIR_REJECTED' },

    GET_ALL_LOCALITE: { type: 'GET_ALL_LOCALITE' },
    GET_ALL_LOCALITE_PENDING: { type: 'GET_ALL_LOCALITE_PENDING' },
    GET_ALL_LOCALITE_FULFILLED: { type: 'GET_ALL_LOCALITE_FULFILLED' },
    GET_ALL_LOCALITE_REJECTED: { type: 'GET_ALL_LOCALITE_REJECTED' },

    GET_ALL_VOIE: { type: 'GET_ALL_VOIE' },
    GET_ALL_VOIE_PENDING: { type: 'GET_ALL_VOIE_PENDING' },
    GET_ALL_VOIE_FULFILLED: { type: 'GET_ALL_VOIE_FULFILLED' },
    GET_ALL_VOIE_REJECTED: { type: 'GET_ALL_VOIE_REJECTED' },

    GET_ALL_DECLARANT: { type: 'GET_ALL_DECLARANT' },
    GET_ALL_DECLARANT_PENDING: { type: 'GET_ALL_DECLARANT_PENDING' },
    GET_ALL_DECLARANT_FULFILLED: { type: 'GET_ALL_DECLARANT_FULFILLED' },
    GET_ALL_DECLARANT_REJECTED: { type: 'GET_ALL_DECLARANT_REJECTED' },

    GET_ALL_SOCIETES_EMETTRICES: { type: 'GET_ALL_SOCIETES_EMETTRICES' },
    GET_ALL_SOCIETES_EMETTRICES_PENDING: { type: 'GET_ALL_SOCIETES_EMETTRICES_PENDING' },
    GET_ALL_SOCIETES_EMETTRICES_FULFILLED: { type: 'GET_ALL_SOCIETES_EMETTRICES_FULFILLED' },
    GET_ALL_SOCIETES_EMETTRICES_REJECTED: { type: 'GET_ALL_SOCIETES_EMETTRICES_REJECTED' },

    CHANGE_RESEARCH_CRITERIA: { type: 'CHANGE_RESEARCH_CRITERIA' },

    DECLARATION_HISTORY_REJECTED: { type: 'DECLARATION_HISTORY_REJECTED' },
    DECLARATION_HISTORY_FULFILLED: { type: 'DECLARATION_HISTORY_FULFILLED' },
    DECLARATION_HISTORY_PENDING: { type: 'DECLARATION_HISTORY_PENDING' },
    DECLARATION_HISTORY: { type: 'DECLARATION_HISTORY' },
};
