FROM mirror-forge.dev.beyond.cegedim.cloud/library/nginx:stable-alpine
EXPOSE 8080
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ./build/ /var/www
COPY configuration.json /etc/configuration.json

CMD ["sh", "-c", "envsubst < /etc/configuration.json > /var/www/configuration && nginx -g 'daemon off;'"]
