<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" targetNamespace="http://ws.cegedimassurance.com/basededroit/wsdl"
xmlns:ns="http://ws.cegedimassurance.com/basededroit/wsdl" xmlns:base_de_droit="http://norme.cegedimassurances.com/base_de_droit">
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://ws.cegedimassurance.com/basededroit/wsdl">
		</xsd:schema>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import
				namespace="http://norme.cegedimassurances.com/base_de_droit"
				schemaLocation="../xsd/base_de_droit/get_info_bdd_request.xsd">
			</xsd:import>
			<xsd:import
				namespace="http://norme.cegedimassurances.com/base_de_droit"
				schemaLocation="../xsd/base_de_droit/get_info_bdd_response.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="getInfoBddRequest">
		<wsdl:part name="getInfoBddRequest" type="base_de_droit:get_info_bdd_request"/>
	</wsdl:message>
	<wsdl:message name="getInfoBddResponse">
		<wsdl:part name="getInfoBddResponse" type="base_de_droit:get_info_bdd_response"/>
	</wsdl:message>
	
	
	<wsdl:portType name="BaseDeDroit">
		<wsdl:operation name="getInfoBdd">
			<wsdl:documentation>Recuperation des données présente dans la base de droit</wsdl:documentation>
			<wsdl:input message="ns:getInfoBddRequest" ></wsdl:input>
			<wsdl:output message="ns:getInfoBddResponse" ></wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>