<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:ns="http://ws.cegedimassurance.com/servicestarification/wsdl"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:commun="http://norme.cegedimassurances.com/commun" xmlns:tarification="http://norme.cegedimassurances.com/tarification" 
	targetNamespace="http://ws.cegedimassurance.com/servicestarification/wsdl">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://ws.cegedimassurance.com/servicestarification/wsdl">
		</xsd:schema>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://norme.cegedimassurances.com/tarification" schemaLocation="../xsd/tarification/requete_justification_calcul.xsd"/>
            <xsd:import namespace="http://norme.cegedimassurances.com/tarification" schemaLocation="../xsd/tarification/reponse_justification_calcul.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="getJustifCalculRequest">
		<wsdl:part name="requete_justification_calcul" type="tarification:requete_justification_calcul" />
	</wsdl:message>

	<wsdl:message name="getJustifCalculResponse">
		<wsdl:part name="reponse_justification_calcul" type="tarification:reponse_justification_calcul" />
	</wsdl:message>


	<wsdl:portType name="ServicesJustificationCalcul">
		<wsdl:operation name="getJustifCalcul">
			<wsdl:documentation>Appel du service justification du calcul.</wsdl:documentation>
			<wsdl:input message="ns:getJustifCalculRequest" />
			<wsdl:output message="ns:getJustifCalculResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="ServicesJustificationCalculBinding" type="ns:ServicesJustificationCalcul">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="getJustifCalcul">
			<soap:operation
				soapAction="http://ws.cegedimassurance.com/servicestarification/wsdl/getJustifCalcul" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="FSIQServicesJustificationCalcul">
		<wsdl:port binding="ns:ServicesJustificationCalculBinding" name="ServicesJustificationCalculPort">
			<soap:address
				location="http://fsiq.services-fm.net/wa-tarification/services/services-tarification/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
