/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    GET_ALL_SERVICES: { type: 'GET_ALL_SERVICES' },
    GET_ALL_SERVICES_FULFILLED: { type: 'GET_ALL_SERVICES_FULFILLED' },

    GET_ALL_CIRCUITS: { type: 'GET_ALL_CIRCUITS' },
    GET_ALL_CIRCUITS_FULFILLED: { type: 'GET_ALL_CIRCUITS_FULFILLED' },

    GET_ALL_CONVENTIONS: { type: 'GET_ALL_CONVENTIONS' },
    GET_ALL_CONVENTIONS_FULFILLED: { type: 'GET_ALL_CONVENTIONS_FULFILLED' },

    GET_LIGHT_DECLARANTS: { type: 'GET_LIGHT_DECLARANTS' },
    GET_LIGHT_DECLARANTS_PENDING: { type: 'GET_LIGHT_DECLARANTS_PENDING' },
    GET_LIGHT_DECLARANTS_FULFILLED: { type: 'GET_LIGHT_DECLARANTS_FULFILLED' },

    GET_ALL_SERVICE_METIER: { type: 'GET_ALL_SERVICE_METIER' },
    GET_ALL_SERVICE_METIER_PENDING: { type: 'GET_ALL_SERVICE_METIER_PENDING' },
    GET_ALL_SERVICE_METIER_FULFILLED: { type: 'GET_ALL_SERVICE_METIER_FULFILLED' },

    GET_ALL_CODES_RENVOI: { type: 'GET_ALL_CODES_RENVOI' },
    GET_ALL_CODES_RENVOI_FULFILLED: { type: 'GET_ALL_CODES_RENVOI_FULFILLED' },

    GET_ALL_GT: { type: 'GET_ALL_GT' },
    GET_ALL_GT_PENDING: { type: 'GET_ALL_GT_PENDING' },
    GET_ALL_GT_FULFILLED: { type: 'GET_ALL_GT_FULFILLED' },

    GET_ALL_LOT: { type: 'GET_ALL_LOT' },
    GET_ALL_LOT_PENDING: { type: 'GET_ALL_LOT_PENDING' },
    GET_ALL_LOT_FULFILLED: { type: 'GET_ALL_LOT_FULFILLED' },

    GET_LOTS_BY_ID: { type: 'GET_LOTS_BY_ID' },
    GET_LOTS_BY_ID_PENDING: { type: 'GET_LOTS_BY_ID_PENDING' },
    GET_LOTS_BY_ID_FULFILLED: { type: 'GET_LOTS_BY_ID_FULFILLED' },

    GET_LOTS: { type: 'GET_LOTS' },
    GET_LOTS_PENDING: { type: 'GET_LOTS_PENDING' },
    GET_LOTS_FULFILLED: { type: 'GET_LOTS_FULFILLED' },
};
