package com.cegedim.next.serviceeligibility.core.utils.exceptions;

import lombok.Getter;

@Getter
public enum ExceptionServiceCode {
  EXCEPTION_TECHNIQUE(10),
  FORMAT_DATE_INCORRECT(11),
  OUT_OF_MAX_PAGINATION(12),
  DECLARANT_EXISTE(20),
  DECLARANT_CRITERE_INVALIDE(21),
  PROFIL_EXISTE(40),
  HABILITATION_EXISTE(50),
  HABILITATION_INEXISTANT(51),
  HABILITATION_EXISTE_WITH_MODIFICATION(52),
  EXCEPTION_DROITS_MAX_RESULTAT(60),

  BENEFICIAIRE_INCONNU(70),
  PRIORISATION_INCORRECTE(14),
  DECLARATION_NON_TROUVEE(15),
  DROIT_RESILIE(31),
  DROIT_SUSPENDU(32),
  CODE_ETAT_INCONNU(80),
  CARTE_PAPIER(81),
  DROIT_NON_OUVERT(33),
  NUM_ADHERENT_ABSENT(72),
  BENEF_NON_ELIGIBLE(71),
  DROITS_VALIDES(34),
  EXCEPTION_VOLUME_DONNEES(61),
  TRANSCO_PARAMETRAGE_INCONNU(99);

  private final Integer code;

  ExceptionServiceCode(Integer code) {
    this.code = code;
  }
}
